export enum COMPANY_SERVICES {
  MAINTENANCE_SCHEDULED = 'MAINTENANCE_SCHEDULED',
  TECHNICAL_RESPONSIBILITY = 'TECHNICAL_RESPONSIBILITY',
  MAINTENANCE = 'MAINTENANCE',
  INSTALLATION = 'INSTALLATION'
} 